# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

branches:
  only:
    - master
    - beta
    - /^greenkeeper.*$/

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm install -g npm@^6
  - appveyor-retry npm i -g bower # for ember-cli-addon-tests
  - npm --version
  - appveyor-retry choco install phantomjs
  - appveyor-retry yarn
  - appveyor-retry yarn add mocha-appveyor-reporter # must be installed locally.


# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - git rev-parse HEAD
  # switch to yarn once ember-cli-addon-tests are removed
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
