name: CI

on:
  pull_request: {}
  push:
    # Filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - beta
      - 'v*'
      - /^greenkeeper.*$/

    # Always run CI for tags
    tags:
      - '*'

  # Early issue detection: run CI weekly on Sundays
  schedule:
  - cron:  '0 6 * * 0'

jobs:
  test-all-packages:
    name: Ember Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Run ember-cli-fastboot Tests
        run: yarn workspace ember-cli-fastboot test:ember
      - name: Run fastboot Tests
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn workspace fastboot test
      - name: Run fastboot-express-middleware Tests
        run: yarn workspace fastboot-express-middleware test
      - name: Run fastboot-app-server Tests
        run: yarn workspace fastboot-app-server test:mocha

  integration-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Integration Tests
        run: yarn workspace integration-tests test

  test-packages:
    name: Test Packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Basic App
        run: yarn workspace basic-app test:mocha
      - name: Custom App
        run: yarn workspace custom-fastboot-app test:mocha
      - name: Run ember-cli-fastboot-testing-app Tests
        run: yarn workspace ember-cli-fastboot-testing-app test:ember

  test-legacy-mocha:
    name: Legacy Mocha Tests - ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 12.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          yarn install --ignore-engines --frozen-lockfile
      - name: Run Mocha Tests
        run: |
          yarn workspace ember-cli-fastboot test:mocha

  try-scenarios:
    name: "ember-try for ember-cli-fastboot: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 7

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --ignore-engines --frozen-lockfile
      - name: test
        run: yarn workspace ember-cli-fastboot ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
