name: CI

on:
  pull_request:
  push:
    # Filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - beta
      - 'v*'
      - /^greenkeeper.*$/

    # Always run CI for tags
    tags:
      - '*'

  # Early issue detection: run CI weekly on Sundays
  schedule:
  - cron:  '0 6 * * 0'

jobs:
  test-mocha:
    name: Mocha Tests - ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 10.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM version 4
        run: |
          npm config set spin false
          npm install -g npm@4
      - name: Remove test packages
          run: rm -rf test-packages
      - name: Yarn Install
        run: yarn install --ignore-engines
      - name: Run Mocha Tests
        run: yarn workspace ember-cli-fastboot test:mocha


  test-ember:
    name: Ember Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 10.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines
      - name: Run Tests
        run: yarn workspace ember-cli-fastboot test:ember

  test-packages:
    name: Test Packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 10.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install --ignore-engines --frozen-lockfile
      - name: Basic App
        run: yarn workspace basic-app test:mocha